/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv'
import { inspect } from 'util'

import { Address } from './Address'
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
})

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'))

export const AddressSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'string',
}
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, 'errors'>
export const isAddress = ajv.compile(AddressSchema) as ValidateFunction<Address>
export function validateAddress(value: unknown): Address {
  if (isAddress(value)) {
    return value
  } else {
    throw new Error(
      ajv.errorsText(
        isAddress.errors!.filter((e: any) => e.keyword !== 'if'),
        { dataVar: 'Address' },
      ) +
        '\n\n' +
        inspect(value),
    )
  }
}
