/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv'
import { inspect } from 'util'

import { Manager } from './Manager'
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
})

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'))

export const ManagerSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  defaultProperties: [],
  definitions: {
    Person: {
      defaultProperties: [],
      properties: {
        address: {
          type: 'string',
        },
        name: {
          type: 'string',
        },
        type: {
          enum: ['person'],
          type: 'string',
        },
      },
      required: ['address', 'name', 'type'],
      type: 'object',
    },
    Salary: {
      defaultProperties: [],
      properties: {
        type: {
          enum: ['salary'],
          type: 'string',
        },
        value: {
          type: 'number',
        },
      },
      required: ['type', 'value'],
      type: 'object',
    },
  },
  properties: {
    person: {
      $ref: '#/definitions/Person',
    },
    salary: {
      $ref: '#/definitions/Salary',
    },
    type: {
      enum: ['employee'],
      type: 'string',
    },
  },
  required: ['person', 'salary', 'type'],
  type: 'object',
}
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, 'errors'>
export const isManager = ajv.compile(ManagerSchema) as ValidateFunction<Manager>
export function validateManager(value: unknown): Manager {
  if (isManager(value)) {
    return value
  } else {
    throw new Error(
      ajv.errorsText(
        isManager.errors!.filter((e: any) => e.keyword !== 'if'),
        { dataVar: 'Manager' },
      ) +
        '\n\n' +
        inspect(value),
    )
  }
}
