/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv'
import { inspect } from 'util'

import { Name } from './Name'
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
})

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'))

export const NameSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'string',
}
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, 'errors'>
export const isName = ajv.compile(NameSchema) as ValidateFunction<Name>
export function validateName(value: unknown): Name {
  if (isName(value)) {
    return value
  } else {
    throw new Error(
      ajv.errorsText(
        isName.errors!.filter((e: any) => e.keyword !== 'if'),
        { dataVar: 'Name' },
      ) +
        '\n\n' +
        inspect(value),
    )
  }
}
